### ISSUE TITLE
No bundle URL present

### ISSUE THREAD

**Issue by MP185496** [callstack/react-native-visionos#103]
### Description

I tried to make fresh install. i fallowed all the steps from instructions and i couldn't load the project. everything pass and project is run but i get the error No bundle URL present. tried everything, to delete node_modules, cache, DerivedData, Pods, build folder. Nothing fixed the issue.
<img width="645" alt="image" src="https://github.com/callstack/react-native-visionos/assets/150946566/9a754a26-4006-42f7-8f23-fef5e9eb477b">

### Steps to reproduce

npx @callstack/react-native-visionos@latest init YourApp
cd YourApp/visionos
bundle install
bundle exec pod install
cd ..
yarn start --port=8087
yarn visionos

### React Native Version

0.73.3

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.6.2
  CPU: (12) arm64 Apple M2 Pro
  Memory: 71.52 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.15.0
    path: ~/.nvm/versions/node/v18.15.0/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.0
    path: ~/.nvm/versions/node/v18.15.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/user/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/user/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.3
    wanted: 0.73.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
No bundle URL present
```

### Reproducer

/

### Screenshots and Videos

<img width="685" alt="image" src="https://github.com/callstack/react-native-visionos/assets/150946566/53ee7042-a440-488d-9f0c-959801c558a4">

**Comment by giovanijfc** [comment]
Hi @MP185496 , you tried initialize metro bundle with yarn start and press reload in simulator error message?

**Comment by MP185496** [comment]
> Hi @MP185496 , you tried initialize metro bundle with yarn start and press reload in simulator error message?

Hi @giovanijfc yes, and it say no apps connected.
<img width="651" alt="image" src="https://github.com/callstack/react-native-visionos/assets/150946566/9f6a4dcb-7bfb-4f74-b87d-89f114b022c6">

**Comment by MP185496** [comment]
I fixed it by this comment: https://stackoverflow.com/a/42612622/23362670
Thank you, sorry for bothering on this.
