### ISSUE TITLE
ToolBar problem

### ISSUE THREAD

**Issue by MP185496** [callstack/react-native-visionos#136]
### Description

Is there a way to add toolbars to our window?
I tried to add it in swift code, but i couldn't because i need view for that, and in our RTC screen we get back a window and window don't have toolbar option on it.

Is there a plan to add this from RN side or to make it work from swift side?
Thanks

### Steps to reproduce

/

### React Native Version

0.73.5

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
/
```

### Stacktrace or Logs

```text
/
```

### Reproducer

/

**Comment by okwasniewski** [comment]
Hey, thanks for opening the issue. Once #137 will be merged and released you will be able to use toolbar modifier and ornaments on the Swift side, like so: 

```swift
@main
struct RC07401VISIONOSApp: App {
  @UIApplicationDelegateAdaptor var delegate: AppDelegate
  
  var body: some Scene {
    WindowGroup {
      RCTRootViewRepresentable(moduleName: "RC07401VISIONOS", initialProps: nil)
        .modifier(WindowHandlingModifier())
        // Add ornaments 
    }
  }
}
```

**Comment by MP185496** [comment]
> Hey, thanks for opening the issue. Once #137 will be merged and released you will be able to use toolbar modifier and ornaments on the Swift side, like so:
> 
> ```swift
> @main
> struct RC07401VISIONOSApp: App {
>   @UIApplicationDelegateAdaptor var delegate: AppDelegate
>   
>   var body: some Scene {
>     WindowGroup {
>       RCTRootViewRepresentable(moduleName: "RC07401VISIONOS", initialProps: nil)
>         .modifier(WindowHandlingModifier())
>         // Add ornaments 
>     }
>   }
> }
> ```

Awsome, thank you very much :)
