### ISSUE TITLE
Styles of `ScreenshotExample` are broken

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#14]
### Description

When navigating to `ScreenshotExample` the user can't see anything except a blank screen. 

Styles of this example are broken

**Comment by matthargett** [comment]
Can you supply a video/screenshot that highlights the problem?

**Comment by okwasniewski** [comment]
Sure! 

This is how it looks currently: 
![Simulator Screenshot - Apple Vision Pro - 2023-10-25 at 21 39 02](https://github.com/callstack/react-native-visionos/assets/52801365/121b1f2e-2a2a-4ee7-80c7-f8e8132e90c6)

**Comment by okwasniewski** [comment]
Ah it's also broken for iOS in RN Core (for dark appearance). So this PR should be contributed to Core

![simulator_screenshot_70817CBA-9A24-4414-9895-30F0C6E97518](https://github.com/callstack/react-native-visionos/assets/52801365/40171c60-ca63-48d1-ac77-12a27ba5ab89)

**Comment by okwasniewski** [comment]
https://github.com/facebook/react-native/pull/41222
