### ISSUE TITLE
Missing Pods

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#15]
### Description

In this issue I want to track Pods that are still missing `visionOS` support that we needed to patch by adding Podspec through `third-party-pods`: 

- `SocketRocket`: https://github.com/facebookincubator/SocketRocket/pull/669

**Comment by derwaldgeist** [comment]
The approach you decribed in your blog worked. However, the package also requires `@react-native-community/netinfo`, which in turn requires CoreTelephony. That's not supported by visionOS, however. So I guess I'll have to find a workaround for this.

**Comment by Sly777** [comment]
`react-native-screens` is missing it atm. I tried to install `react-navigation` but it always gives an error: `require native component rnsscreenstackheaderconfig was not found in the UIManager` and when I checked the podfile, `RNScreens` was missing different between ios and visionos. @okwasniewski

**Comment by okwasniewski** [comment]
Hey @Sly777, 

I'm still working on the PR: https://github.com/software-mansion/react-native-screens/pull/2025

I'm hoping to get it merged today 🤞

**Comment by Sly777** [comment]
AWEEESSSOMEEEEEEE 🔥 🔥  @okwasniewski

**Comment by thiagobrez** [comment]
Hey @derwaldgeist just FYI, `@react-native-community/netinfo` now also has support for visionOS: https://github.com/react-native-netinfo/react-native-netinfo/pull/714

`CoreTelephony` is not supported indeed, but then it falls back to the lower-level `ifaddrs`, which is the same approach done for macOS, tvOS and Catalyst, since they also do not support telephony

**Comment by okwasniewski** [comment]
Looks like https://github.com/facebookincubator/SocketRocket/releases/tag/0.7.1 has been released!

**Comment by okwasniewski** [comment]
Merging this PR should close the issue: https://github.com/facebook/react-native/pull/46300

**Comment by okwasniewski** [comment]
PR merged!
