### ISSUE TITLE
Trigger Dev Menu from the device

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#17]
### Description

Currently, the only way to trigger Dev Menu is by clicking "d" while having Metro open. 

I want to implement a way to trigger Dev Menu from the actual device. I was thinking about recognizing the triple click of the digital crown (not available on the simulator) but Im open for suggestions.

**Comment by matthargett** [comment]
I'll ask Apple what "rare" gestures we can use to trigger on both devkit and simulator, but also suggest they add triple click into simulator.
