### ISSUE TITLE
Opening Accessibility API example - `unrecognized selector sent to instance`

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#30]
### Description

When opening Accessibility API example error is thrown `unrecognized selector sent to instance`

![CleanShot 2023-11-10 at 17 36 02@2x](https://github.com/callstack/react-native-visionos/assets/52801365/3d135b46-3137-4775-bdb3-972148d514c5)

**Comment by gokul1099** [comment]
@okwasniewski  Can you check this again? ,it works for me. 

![Simulator Screenshot - Apple Vision Pro - 2023-12-08 at 12 48 25](https://github.com/callstack/react-native-visionos/assets/42144106/2c4144d6-7ca1-4605-8810-d1b39a227c96)

**Comment by okwasniewski** [comment]
Thanks for checking @gokul1099! Yeah, it works now, I guess it got fixed by some other PR or a rebase.
