### ISSUE TITLE
Setup SwiftUI as the entry point 

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#45]
### Description

To allow for `visionOS` specific APIs we need to setup SwiftUI as the entry point to visionOS apps. 

The idea is to have `UIViewRepresentable` holding react native root view which would allow us to use: ImmersiveSpaces, volumetric windows and ornaments

**Comment by derwaldgeist** [comment]
I was just going to ask this. We're devloping a fully immersive AR app. In our case, the best combination would be to have the opportunity to use SwiftUI alongside React Native, so one can profit from both technologies.

(I used Cordova in the past, not React Native, and there were always cases where the only solution would have been to integrate some native UX or plugins.)

**Comment by derwaldgeist** [comment]
Woah, that's amazing! Great work, guys. Love it.

**Comment by okwasniewski** [comment]
@derwaldgeist Sorry I missed your response. Yes it will be possible to place content everywhere same as in native apps (as RealityKit capabilities are the only limit here).

SwiftUI entrypoint is now on main branch, so I'm closing this issue.
