### ISSUE TITLE
Alert with many buttons is cut off 

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#59]
### Description

In the Alert example, the alert with many buttons is cut off the screen

![CleanShot 2023-12-15 at 10 33 58@2x](https://github.com/callstack/react-native-visionos/assets/52801365/3d2fa527-5c19-4022-8697-97cf95f7ea50)

**Comment by Marcoo09** [comment]
Am I doing something wrong to reproduce the issue?
![image](https://github.com/callstack/react-native-visionos/assets/18408823/d84395fb-23ba-4c86-86bf-3c3f8f9ee98b)

**Comment by okwasniewski** [comment]
@Marcoo09 Which beta are you running? Maybe it's a regression in the latest one

**Comment by Marcoo09** [comment]
I'm using Xcode 15.1 beta and visionOS 1 beta 6

**Comment by okwasniewski** [comment]
@Marcoo09 Im running Xcode 15.2 beta with visionOS Beta 7, can you check it on the newer sdk?

**Comment by Marcoo09** [comment]
@okwasniewski sorry for the delay, I'll check it tomorrow!

**Comment by okwasniewski** [comment]
For me this is still happening even on Xcode 15.2 stable

**Comment by okwasniewski** [comment]
I've double checked this in SwiftUI application and the same thing is happening - I'm closing this

![CleanShot 2024-03-22 at 15 58 32@2x](https://github.com/callstack/react-native-visionos/assets/52801365/2d830271-a886-44b9-8ea6-c4abd3bda3ee)
