### ISSUE TITLE
Mark `Keyboard` module as unsupported on VisionOS

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#6]
### Description

Goal of this issue is to mark `Keyboard` module as unsupported for VisionOS. 

As stated in Apple docs: https://developer.apple.com/documentation/uikit/uikeyboardwillshownotification?language=objc : 

> An app running in visionOS never receives this notification. The system displays the keyboard in a separate window, leaving the app’s window unaffected by the keyboard’s appearance and disappearance.

Goals: 
- Avoid registering listeners inside `RCTKeyboardObserver` (`#if TARGET_OS_VISION`)
- Mark `Keyboard` and `KeyboardAvoidingView` as not supported

**Comment by thiagobrez** [comment]
I can take this one!

**Comment by thiagobrez** [comment]
@okwasniewski PR #25 is open for review, but I'm getting a memory leak. Probably related to the changes in `RCTKeyboardObserver` but did not find the culprit yet.

```
WARN  Sending `didReceiveNetworkData` with no listeners registered.
WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
WARN  Sending `didSendNetworkData` with no listeners registered.
WARN  Sending `didSendNetworkData` with no listeners registered.
WARN  Sending `didSendNetworkData` with no listeners registered.
WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
```

Will continue investigating, but sending here in case you see something I don't!

**Comment by TMisiukiewicz** [comment]
@thiagobrez I had the same issue, it was a bug in the core and it was already reverted:
https://github.com/facebook/react-native/commit/8ac47faf32dae1744f93dae711b9c92bfe783c23
https://github.com/facebook/react-native/commit/4e04ff5610b0f20c59701920a165c46f21ef2446

**Comment by thiagobrez** [comment]
Yeah thanks @TMisiukiewicz! @okwasniewski also warned me about it, good to know 🙏🏻 

So I'll just wait for it to be synced and re-test

**Comment by derwaldgeist** [comment]
I actually was confused by this message. Does it mean that React Native visionOS apps cannot use text input? Or is it just related to a certain way to hook into keyboard notifications, i.e. when the keyboard pops up?

**Comment by okwasniewski** [comment]
I think refining this message as `Keyboard API is not available on visionOS platform.` would be better. visionOS supports text inputs but doesn't support receiving events and imperatively controlling the keyboard.

I will re-open this issue to take care of this. I also noticed that this pops up when user is not using Keyboard API

**Comment by derwaldgeist** [comment]
Yes, makes sense. Does this also mean that keyboard events won't work in general? Like to check if the enter key has been pressed in an input field?

**Comment by okwasniewski** [comment]
@derwaldgeist Keyboard API doesn't handle this. You can use TextInput's `onSubmitEditing` callback to detect when user pressed the enter (submit key).
