### ISSUE TITLE
Hover style API: variable border radius 

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#69]
### Description

The goal of this issue is to adapt hoverStyle API to properly use variable corner radius for each corner of the view. This is a continuation of the work done in #66

**Comment by okwasniewski** [comment]
@gokul1099 Created an issue for the feature you was working on

**Comment by gokul1099** [comment]
@okwasniewski  while working for PR #66 I made all the changes in RCTViewComponentView file and it works. But after recent commits any changes in RCTViewComponentView is not reflecting. I even added breakpoint and it's not working.
Any recent changes are causing this ?  Any idea on this ??

**Comment by okwasniewski** [comment]
@gokul1099 Can you try installing pods with RCT_NEW_ARCH_ENABLED=1 flag? Recently in core they changed that RNTester is not building with new arch by default

**Comment by gokul1099** [comment]
> @gokul1099 Can you try installing pods with RCT_NEW_ARCH_ENABLED=1 flag? Recently in core they changed that RNTester is not building with new arch by default

oh ok, let me try

**Comment by gokul1099** [comment]
> @gokul1099 Can you try installing pods with RCT_NEW_ARCH_ENABLED=1 flag? Recently in core they changed that RNTester is not building with new arch by default

I tried this still not working

**Comment by gokul1099** [comment]
@okwasniewski  I don't think this is specific to hoverStyle prop. Currently none of the methods in the RCTViewComponentView is being invoked.

**Comment by okwasniewski** [comment]
This feature has been tackled by @saadnajmi in this PR: https://github.com/facebook/react-native/pull/43078 - which will be soon cherry-picked to react-native-visionos

**Comment by okwasniewski** [comment]
fixed by: #114
